# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-29 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20161129_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='index_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=256, upload_to='index/')),
                ('subtitle', models.TextField(max_length=4096)),
                ('slider_delay', models.IntegerField()),
            ],
        ),
    ]
