# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-29 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_index_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=256, upload_to='slider/')),
                ('description', models.TextField(max_length=4096)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
    ]
