# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-29 13:36
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=265)),
                ('school', models.CharField(max_length=512)),
                ('college', models.CharField(max_length=512)),
                ('grade', models.CharField(max_length=265)),
                ('order', models.PositiveIntegerField(default=0)),
                ('avatar', models.ImageField(max_length=256, upload_to='avatar/')),
                ('card', models.ImageField(max_length=256, upload_to='card/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('time_slot', web.models.ListField()),
            ],
        ),
    ]
