# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20161129_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.BooleanField(choices=[(0, 'Male'), (1, 'Female')], default=0),
        ),
    ]
