# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_teacher_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=265)),
                ('phone_num', models.CharField(max_length=32)),
                ('address', models.TextField(max_length=2048)),
                ('ctime', models.DateTimeField(auto_now=True)),
                ('time_slot', models.TextField(default='[]', max_length=4096)),
                ('status', models.IntegerField(choices=[(0, '未处理'), (1, '成功'), (2, '失效')], default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='web.teacher')),
            ],
        ),
    ]
