# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-06 01:16
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='system_setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_account', models.CharField(max_length=64, verbose_name='信息平台账号')),
                ('msg_pwd', models.CharField(max_length=32, verbose_name='信息平台密码')),
            ],
            options={
                'verbose_name': '系统设置（谨慎操作）',
                'verbose_name_plural': '系统设置（谨慎操作）',
            },
        ),
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name': '关于我们', 'verbose_name_plural': '关于我们'},
        ),
        migrations.AlterModelOptions(
            name='index_info',
            options={'verbose_name': '首页信息', 'verbose_name_plural': '首页信息'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': '家教预约', 'verbose_name_plural': '家教预约'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': '首页滚动图', 'verbose_name_plural': '首页滚动图'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '教师', 'verbose_name_plural': '教师'},
        ),
        migrations.AlterField(
            model_name='about_us',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='富文本编辑'),
        ),
        migrations.AlterField(
            model_name='index_info',
            name='image',
            field=models.ImageField(max_length=256, upload_to='index/', verbose_name='首页logo'),
        ),
        migrations.AlterField(
            model_name='index_info',
            name='slider_delay',
            field=models.IntegerField(verbose_name='滚动间隔时间(单位为毫秒)'),
        ),
        migrations.AlterField(
            model_name='index_info',
            name='subtitle',
            field=models.TextField(max_length=4096, verbose_name='logo下文字'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='address',
            field=models.TextField(max_length=2048, verbose_name='预约人地址'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ctime',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=265, verbose_name='预约人'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_num',
            field=models.CharField(max_length=32, verbose_name='预约人电话'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(0, '未处理'), (1, '成功'), (2, '失效')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='web.teacher', verbose_name='预约教师'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_slot',
            field=models.TextField(default='[]', max_length=4096, verbose_name='预约时段'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(max_length=4096, verbose_name='相关描述'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(max_length=256, upload_to='slider/', verbose_name='轮播图片'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='order',
            field=models.PositiveIntegerField(verbose_name='轮播顺序(由0开始)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(max_length=256, upload_to='avatar/', verbose_name='头像图片'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='card',
            field=models.ImageField(max_length=256, upload_to='card/', verbose_name='校园卡图片'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='college',
            field=models.CharField(max_length=512, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.BooleanField(choices=[(False, 'Male'), (True, 'Female')], default=False, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='grade',
            field=models.CharField(max_length=265, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=265, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='顺序(由0开始)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.CharField(max_length=512, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=1024, verbose_name='科目（空格分隔）'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='time_slot',
            field=models.TextField(default='[]', max_length=4096, verbose_name='时段（不在这里修改）'),
        ),
    ]
